#!/usr/bin/env node
// tools/build.mjs — assemble the single-file game.
//
//   node tools/build.mjs [--out path/to/file.html]
//
// Reads  src/index.template.html  and src/js/*.js  and assets/*.glb,  writes  knights_out_final.html
// (repo root) by filling three placeholders in the template:
//   <!-- @@THREE_SCRIPTS@@ -->  CDN three r147 + GLTFLoader + SkeletonUtils + PointerLockControls <script src> tags
//   <!-- @@ASSETS@@ -->         one <script> with  window.ASSETS = { name: "data:model/gltf-binary;base64,..." }
//   <!-- @@MODULES@@ -->        one <script> per module, in the fixed order below (an error in one module
//                              does not stop the following scripts from running)
// Plain node, no dependencies, deterministic output (no timestamps), so rebuilding does not churn diffs.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

// ---- configuration ---------------------------------------------------------------------------------------------
const THREE_VERSION = '0.147.0';   // r147: the last release shipping the non-module examples/js builds
const CDN = `https://cdn.jsdelivr.net/npm/three@${THREE_VERSION}`;
const CDN_SCRIPTS = [
  `${CDN}/build/three.min.js`,
  `${CDN}/examples/js/loaders/GLTFLoader.js`,
  `${CDN}/examples/js/utils/SkeletonUtils.js`,
  `${CDN}/examples/js/controls/PointerLockControls.js`,
];

// Only assets the game actually uses are embedded (Frog / pistol are not).
const USED_ASSETS = [
  'knight', 'knight_helmet1', 'knight_shield', 'knight_boss_shield', 'knight_sword',
  'revolver', 'birch_tree', 'grass', 'grass_2', 'rock',
];

// Script order matters (docs/FIX_PLAN.md section 2).
const MODULES = [
  'assets', 'world', 'sfx', 'hud', 'fx', 'weapon', 'combat',
  'enemies', 'boss', 'waves', 'game', 'touch', 'grenade', 'debug', 'main',
];

const PLACEHOLDERS = {
  three: '<!-- @@THREE_SCRIPTS@@ -->',
  assets: '<!-- @@ASSETS@@ -->',
  modules: '<!-- @@MODULES@@ -->',
};

// ---- helpers ---------------------------------------------------------------------------------------------------
function fail(msg) {
  console.error('build: ' + msg);
  process.exit(1);
}

function readText(rel) {
  const p = path.join(ROOT, rel);
  if (!fs.existsSync(p)) fail(`missing file ${rel}`);
  return fs.readFileSync(p, 'utf8');
}

// Make arbitrary JS safe to inline in a <script> element.
function inlineSafe(code, label) {
  if (/<!--/.test(code)) console.warn(`build: warning: ${label} contains "<!--" (can confuse the HTML parser inside <script>)`);
  return code.replace(/<\/script/gi, '<\\/script');
}

// ---- args ------------------------------------------------------------------------------------------------------
let outPath = path.join(ROOT, 'knights_out_final.html');
const argv = process.argv.slice(2);
for (let i = 0; i < argv.length; i++) {
  if (argv[i] === '--out') outPath = path.resolve(process.cwd(), argv[++i] || fail('--out needs a path'));
  else fail(`unknown argument ${argv[i]}`);
}

// ---- build -----------------------------------------------------------------------------------------------------
let html = readText('src/index.template.html');
for (const [k, ph] of Object.entries(PLACEHOLDERS)) {
  if (!html.includes(ph)) fail(`template is missing the placeholder ${ph}`);
  if (html.split(ph).length !== 2) fail(`template has more than one ${ph}`);
}

const threeTags = CDN_SCRIPTS.map(u => `<script src="${u}"></script>`).join('\n  ');

let assetBytes = 0;
const assetLines = ['window.ASSETS = {};'];
for (const name of USED_ASSETS) {
  const rel = `assets/${name}.glb`;
  const p = path.join(ROOT, rel);
  if (!fs.existsSync(p)) fail(`missing asset ${rel}`);
  const buf = fs.readFileSync(p);
  assetBytes += buf.length;
  assetLines.push(`window.ASSETS[${JSON.stringify(name)}] = "data:model/gltf-binary;base64,${buf.toString('base64')}";`);
}
const assetsTag = `<script>\n${assetLines.join('\n')}\n</script>`;

const moduleTags = MODULES.map(name => {
  const rel = `src/js/${name}.js`;
  const code = inlineSafe(readText(rel), rel).replace(/\s+$/, '');
  return `<script>\n${code}\n//# sourceURL=${rel}\n</script>`;
}).join('\n');

// function replacers: the replacement strings contain "$" sequences in base64/JS that must not be interpreted
html = html
  .replace(PLACEHOLDERS.three, () => threeTags)
  .replace(PLACEHOLDERS.assets, () => assetsTag)
  .replace(PLACEHOLDERS.modules, () => moduleTags)
  .replace(/^(<!DOCTYPE html>[ \t]*\r?\n)/i, (m) => m + '<!-- GENERATED by tools/build.mjs from src/ and assets/ - edit those, not this file. -->\n');

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, html);

const kb = (n) => (n / 1024).toFixed(0) + ' KB';
console.log(`build: wrote ${path.relative(ROOT, outPath) || outPath}  (${kb(Buffer.byteLength(html))}; ${USED_ASSETS.length} assets = ${kb(assetBytes)} raw, ${MODULES.length} modules)`);
